# Generated by Django 4.1.6 on 2023-03-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0003_alter_taskinfo_task_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Team_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Activity_name', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('Team_description', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField(blank=True, null=True)),
                ('User_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('User_Role', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
    ]
